# Generated by Django 5.1 on 2026-04-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(default="Scheduled", max_length=20),
        ),
    ]
